services:
  postgres:
    image: postgres:16-alpine
    container_name: lulesmarket-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lulesmarket-db
    volumes:
      - lulesmarket-db:/var/lib/postgresql/data

volumes:
  lulesmarket-db:
    driver: local
