name: CI

on:
  pull_request:
    branches: [main, dev]

jobs:
  validate:
    name: Code Quality (Lint, Typecheck, Test)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run Biome Check
        run: bun check

      - name: Type Check
        run: bun type-check

      - name: Run tests (unit)
        run: bun test:unit
        env:
          NEXT_TELEMETRY_DISABLED: 1
          APP_URL: ${{ secrets.APP_URL }}
          S3_REGION: ${{ secrets.AWS_REGION }}
          S3_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL_S3 }}
          S3_BUCKET_URL: ${{ secrets.S3_BUCKET_URL }}
          S3_ENDPOINT_URL_IAM: ${{ secrets.AWS_ENDPOINT_URL_IAM }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          MP_WEBHOOK_SECRET: ${{ secrets.MP_WEBHOOK_SECRET }}
          MP_ACCESS_TOKEN: ${{ secrets.MP_ACCESS_TOKEN }}
          BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_NAME: ${{ secrets.ADMIN_NAME }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SUPER_ADMIN_EMAIL: ${{ secrets.SUPER_ADMIN_EMAIL }}
          SUPER_ADMIN_PASSWORD: ${{ secrets.SUPER_ADMIN_PASSWORD }}
          SUPER_ADMIN_NAME: ${{ secrets.SUPER_ADMIN_NAME }}
          NEXT_PUBLIC_BETTER_AUTH_URL: ${{ secrets.NEXT_PUBLIC_BETTER_AUTH_URL }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
          GITHUB_CLIENT_ID: ${{ secrets.GHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GHUB_CLIENT_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Cache Next.js build cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Build
        run: bun run build
        env:
          NEXT_TELEMETRY_DISABLED: 1
          APP_URL: ${{ secrets.APP_URL }}
          S3_REGION: ${{ secrets.AWS_REGION }}
          S3_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL_S3 }}
          S3_BUCKET_URL: ${{ secrets.S3_BUCKET_URL }}
          S3_ENDPOINT_URL_IAM: ${{ secrets.AWS_ENDPOINT_URL_IAM }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          MP_WEBHOOK_SECRET: ${{ secrets.MP_WEBHOOK_SECRET }}
          MP_ACCESS_TOKEN: ${{ secrets.MP_ACCESS_TOKEN }}
          BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_NAME: ${{ secrets.ADMIN_NAME }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SUPER_ADMIN_EMAIL: ${{ secrets.SUPER_ADMIN_EMAIL }}
          SUPER_ADMIN_PASSWORD: ${{ secrets.SUPER_ADMIN_PASSWORD }}
          SUPER_ADMIN_NAME: ${{ secrets.SUPER_ADMIN_NAME }}
          NEXT_PUBLIC_BETTER_AUTH_URL: ${{ secrets.NEXT_PUBLIC_BETTER_AUTH_URL }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
          GITHUB_CLIENT_ID: ${{ secrets.GHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GHUB_CLIENT_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
