name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps
      - name: Run Playwright tests
        run: bunx playwright test
        env:
          NEXT_TELEMETRY_DISABLED: 1
          APP_URL: ${{ secrets.APP_URL }}
          S3_REGION: ${{ secrets.S3_REGION }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL_S3 }}
          S3_BUCKET_URL: ${{ secrets.S3_BUCKET_URL }}
          S3_ENDPOINT_URL_IAM: ${{ secrets.S3_ENDPOINT_URL_IAM }}
          S3_ENDPOINT_URL_S3: ${{ secrets.S3_ENDPOINT_URL_S3 }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          MP_WEBHOOK_SECRET: ${{ secrets.MP_WEBHOOK_SECRET }}
          MP_ACCESS_TOKEN: ${{ secrets.MP_ACCESS_TOKEN }}
          BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_NAME: ${{ secrets.ADMIN_NAME }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SUPER_ADMIN_EMAIL: ${{ secrets.SUPER_ADMIN_EMAIL }}
          SUPER_ADMIN_PASSWORD: ${{ secrets.SUPER_ADMIN_PASSWORD }}
          SUPER_ADMIN_NAME: ${{ secrets.SUPER_ADMIN_NAME }}
          NEXT_PUBLIC_BETTER_AUTH_URL: ${{ secrets.NEXT_PUBLIC_BETTER_AUTH_URL }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
          GITHUB_CLIENT_ID: ${{ secrets.GHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GHUB_CLIENT_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
